
work_dir: ./work_dir/ntu120_xsub_2021_angular_test

# feeder
feeder: feeders.feeder.Feeder

test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_joint.npy
  label_path: ./data/ntu120/xsub/val_label.pkl

# model
model: model.network.Model
model_args:
  in_channels: 15
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # ablation
  ablation: sgcn_only


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30,40,50]

num_epoch: 60
device: [0,1]
batch_size: 40
forward_batch_size: 40
test_batch_size: 40
nesterov: True

optimizer: SGD

eval_start: 5
eval_interval: 5

phase: test
weights: "PATH TO THE PRETRAINED MODEL"
save_score: True
